### ISSUE TITLE
Multismelter doesnt smelt proper quantities during continuous operation

### ISSUE THREAD

**Issue by ogmon1243** [GregTechCEu/GregTechCEu-1.19#1403]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Monifactory

### Expected Behavior

Just gonna link the original issue from another git here. 
https://github.com/ThePansmith/Monifactory/issues/312

Its an issue with multismelter parallelization not smelting proper quanities of items.

### Actual Behavior

check git link

### Steps to Reproduce

check git link

**Comment by YiRanMushroom** [comment]
This is probably because of the parallel logic. There should be a property called alwaysTryToModifyRecipe which is automatically set to true. This would cause the machine not to recalculate the parallel if previous calculation can still be run. This is probably good for performance, however as I tested, even in UV stage, the performance difference is still trivia, so I don't actually know what is the point of the property.

**Comment by YoungOnionMC** [comment]
fixed in #1461
