### ISSUE TITLE
4A/16A energy hatches don't overclock

### ISSUE THREAD

**Issue by geradeaus007** [GregTechCEu/GregTechCEu-1.19#2257]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Minecraft Version

1.20.1

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

GTCEu Modern 1.4.6 dependencies

### Expected Behavior

4A/16A hatches do overclock.

### Actual Behavior

They don't.

### Steps to Reproduce

1. Build any multiblock
2. Add a 4A/16A energy hatch to it
3. See "Max Recipe Tier" stuck at energy hatch voltage tier while "Max EU/t" shows the correct tier

### Additional Information

I tested it with LCRs and the EV and IV versions of the hatches.
4A EV:
![image](https://github.com/user-attachments/assets/07b79995-1582-4805-a515-8cb68818f019)
Here the voltage tier is 1 tier below actual voltage tier.

16A EV:
![image](https://github.com/user-attachments/assets/a8ca0ede-1c82-446c-8589-7fca1144eda7)
Note that this is 2 tiers below actual voltage tier. (kinda funny to see ngl)

Dynamo hatches with multiple amperes work as intended.
Similar to this issue is #2017, although that did fix the overclock from 2x 2A hatches.

**Comment by krossgg** [comment]
This is intended. In order to increase the recipe tier of a multiblock, you have to use *two* separate energy hatches. By doing this, you can only increase the tier by one. Note that if you add on a regular energy hatch next to your 4A or 16A hatch, the recipe tier *will* increase as expected. The max EU/t line shows how much EU/t you have available for overclocking or parallelization.
