### ISSUE TITLE
Chunks becoming corrupted

### ISSUE THREAD

**Issue by FaltEarthren** [GregTechCEu/GregTechCEu-1.19#2363]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

Gregtech Modern 1.5.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Dedicated Server; hosted on my computer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Monifactory 1.10.1

### Expected Behavior

Chunks Exist and are not corrupted
![image](https://github.com/user-attachments/assets/8bfcab75-1a1a-4c9f-9df9-02e1ede1279c)

### Actual Behavior

Chunk is corrupted, all 8 chunks around are not rendered, but can be interacted with
![image](https://github.com/user-attachments/assets/657c781a-e77a-48cb-a277-00d4d0dd61c8)

Another players server
![image](https://github.com/user-attachments/assets/ab6899ed-7d13-48d3-ae1c-12cc3d225cdf)

### Steps to Reproduce

Updating the modpack from 0.10.0 to 0.10.1 creates the issue in the same chunk

### Additional Information

The chunk is force loaded with ftb chunks (I think), and all surrounded chunks are are claimed. All other gt machines in my base are fine.

**Comment by HexFlareheart** [comment]
I can provide a bit more information on this one, as at least two separate instances of this particular issue have appeared on my server, only one of which I've personally witnessed.

The surrounding 8 chunks not rendering is because of Embeddium; turning it off will have all but the affected chunk render, as well as any chunks relatively "behind" the affected chunk from the player's POV. I assume this is a culling error that's occurring as a side effect of the chunk error.

I also believe this is _not_ a full chunk corruption, and may in fact be a communication error between the server and client; the affected chunks only seem to be affected on clientside, and appear to be perfectly fine serverside. This is evident in part because the collision still exists on serverside (and thus the desync between client and server can cause horrible glitchy collision movements), but also in part because the instance of this that I directly witnessed **fixed itself**, with the chunk inexplicably starting working clientside after a great deal of restarts of both client and server. I do not know what caused this to happen.

![image](https://github.com/user-attachments/assets/bb91cd4e-4eaa-4c76-81a5-1fb6ea765358)
![image](https://github.com/user-attachments/assets/1ca7cede-f310-43bd-8bfd-cebfaaab098d)

Otherwise, similar scenario in the chunk error I witnessed- chunk was force loaded (by the Chunk Loaders mod rather than FTB Chunks), and contained a selection of GregTech machines. The affected chunk includes a Steam Additions Steam Foundry as well as the bulk of my machines at the time; on the second screenshot, it starts directly to the right of the centrifuge array on the left. As far as I know, though Steam Additions had _not_ been updated at the time, it _was not_ the Steam Foundry that caused this, as despite the fluid changes I'd tested it a fair bit before to ensure it did, in fact, work.

I also did not change any settings or mods on the server in between first observing the chunk error and it fixing itself.

**Comment by HexFlareheart** [comment]
![image](https://github.com/user-attachments/assets/01580985-435a-4a8f-8fb5-608b8a9cc20b)
![image](https://github.com/user-attachments/assets/f976d07a-a6c1-4141-b837-aa1d106513e2)

Found the other instance of this error on my server, and fortunately(?) this one _is_ still extant. I don't know the full scope of what's in this chunk, but I do know it is _also_ force loaded, and it has a coke oven in it. Notably, you can also see wires connecting into blocks within the chunk, and I have seen mobs wander into it without issue, supporting the assumption that this is a clientside issue, albeit a very weird and persistent one.

[debug (chunk error).log](https://github.com/user-attachments/files/17769911/debug.chunk.error.log)
[debug (serverside).log](https://github.com/user-attachments/files/17769929/debug.serverside.log)

I grabbed the debug log from both sides from finding this, though it doesn't look like it contains any useful information. Can provide world download and Prism profile, but given the seemingly ephemeral nature of this particular error I can't guarantee it'll still be present on the other end. (Also the world's kind of very large is the other caveat. I pregenerated a significant portion of it for lag reduction purposes.)

**Comment by ObKo** [comment]
Got same issue. Looks like some issue with client<->server channel, because I've also got #2351 with 1.5.1 update
