### ISSUE TITLE
Crash when clicking some items in JEI

### ISSUE THREAD

**Issue by aAndrew3030** [GregTechCEu/GregTechCEu-1.19#300]
### GregTech CEu Version

1.0.11

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

-

### Actual Behavior

-

### Steps to Reproduce

-

### Additional Information

Viewing the uses for some items in JEI cause the server to crash. I am not experiencing this issue with any other mods, only GT

[crash-2023-08-14_19.45.14-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12352091/crash-2023-08-14_19.45.14-client.txt)

**Comment by aAndrew3030** [comment]
It shows "ldlib" as the cause, is this a dependency that needs to be installed? If so it is not listed as such

**Comment by MasterSparkInYourFace** [comment]
ldlib is definitely shown installed in the list of mods. the reason forge suspects ldlib is probably because they have mixins that interact with JEI. I looked ldlib up on curseforge and modrinth, but I can't figure out what in your modpack it's a dependency for, so you might want to try to remove it and see if minecraft croaks at you.

No other mod has mixins in JEI, so the most likely reason for this crash is that ldlib doesn't know how to handle something about gregtech items properly

**Comment by aAndrew3030** [comment]
I can say with 100% certainty ldlib is not installed as a mod in my mods folder. I checked everything several times for the mod, and also checked dependencies that are listed on curseforge. That said, a quick search of the GT code shows ldlib code in the GT mod, and that is why I was asking if it is a dependency? Are you a dev for this mod? I am now more confused then ever

**Comment by aAndrew3030** [comment]
I know nothing about coding, but does this show it as a dependency for the forge version?

https://github.com/GregTechCEu/GregTech-Modern/blob/1.20.1-HOTFIX/settings.gradle

**Comment by Fuyukai** [comment]
ldlib is bundled within the jar.
