### ISSUE TITLE
Gregtech 1.20.1 crashes on Quilt

### ISSUE THREAD

**Issue by whyareyoulookingatthis** [GregTechCEu/GregTechCEu-1.19#355]
### GregTech CEu Version

1.0.11.b-build_168

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

Expected to launch the game.

### Actual Behavior

The game crashed before loading to the title screen

### Steps to Reproduce

1) Install Gregtech 1.0.11.b-build_168, Quilted Fabric API 7.2.1+0.88.0-1.20.1 and Quilt Loader 0.21.0-beta.2
2) Launch the game.

Minecraft will crash before loading the title screen.

### Additional Information

https://mclo.gs/fLpmWLE
Used MixinTrace for this log but the crash still happens without MixinTrace.

**Comment by whyareyoulookingatthis** [comment]
Still happens on 1.0.12.c-build_190

**Comment by Desenrrollado** [comment]
I suffer from similar however, I'm running the following.

Latest version of Quilt for 1.20.1
0.21.0-beta.4

Quilt Fabric Api:
QFAPI 7.2.2 and QSL 6.1.2

Latest Version of Greg:
GregTechCEu 1.20.1-1.0.12.e-fabric

It won't crash on loading Quilt like Beta 2 on trying to launch the game. 

I can generate the world just fine, and run it. The issue comes from relaunching and trying to use the world. It crashes shortly after from affected chunk generation. Seemingly from jungle bamboo. I'm not running any other mods besides those two during testing. I have ran it in my main and the same pretty much happens. 

Previously it the result of crashes was different and related to the warden's biome and blocks. Though those were previous versions. Those seem resolved now. It's just weird how it changes.
___________________________________________________________________________________________________________________________________
Stock Quilt Beta 4:

Crash:
[crash-2023-09-22_12.05.08-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12703528/crash-2023-09-22_12.05.08-server.txt)

Log: 
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/12703535/latest.log)

___________________________________________________________________________________________________________________________________
Main mod pack:

Crash:
[crash-2023-09-22_11.46.41-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12703545/crash-2023-09-22_11.46.41-server.txt)

Log: 
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/12703550/latest.log)

**Comment by rinOfTheStars** [comment]
Possibly a bug in QFAPI considering it doesn't crash on FAPI—will look into this in a moment to see if it can be fixed on the QFAPI end or if it's something that GTCE Modern needs to fix themselves

**Comment by rinOfTheStars** [comment]
Can't replicate the first crash on GTCEU Modern `1.0.12.e` + QLoader `0.20.2` + QFAPI `7.2.2+0.88.1-1.20.1`

Second crash replicated. Going to test against FAPI to make sure it's a QFAPI specific bug...

**Comment by rinOfTheStars** [comment]
Yup, crash doesn't occur under QLoader + FAPI. Going to try sticking it under a debugger to see if I can figure out what's wrong.

**Comment by rinOfTheStars** [comment]
It's due to something odd going on in the way features are added to biomes. Not sure whose side it's actually on, but I'm leaning towards it being a _very_ obscure bug in QSL.

**Comment by rinOfTheStars** [comment]
> It's due to something odd going on in the way features are added to biomes. Not sure whose side it's actually on, but I'm leaning towards it being a _very_ obscure bug in QSL.

HAHA NOPE IT'S WORSE

Whatever this bug is, it's *not* due to solely QSL, considering #409 exists—QSL just makes it happen consistently in non-superflat worlds, while a mod has to do whatever causes the crash to happen with pure FAPI

**Comment by screret** [comment]
still happens on latest dev?
