### ISSUE TITLE
Axe Duplication Glitch

### ISSUE THREAD

**Issue by EntityIridescent** [GregTechCEu/GregTechCEu-1.19#744]
### GregTech CEu Version

1.0.20b

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

Two axes should be able to be combined in the crafting table to form one with a higher durability.

### Actual Behavior

Two axes form another axe with higher durability without consuming the first two axes. 

### Steps to Reproduce

1. Use a portion of two axes of the same material
2. Combine them in a crafting table
3. Duplicate to your heart's content

### Additional Information

I have not tested whether or not this works with other tools or how it affects initial enchantments on specific tools.

**Comment by Exzept1on** [comment]
can confirm this

**Comment by StellaBiscuit** [comment]
Happens with every GT tools

This is most likely happening due to tools, when used in recipes, consume 1 durability instead of themselves, this behaviour then breaks the vanilla repairing as the tool only lose 1 durability instead of being consumed, allowing for infinite tools

Enchanted tools like Invar looses the enchant as expected with Vanilla repairing (Not the original tools tho), the same issue happens with Ironwood tools in Twilight Forest
Not that it really matter since the Grindstone can already remove the default enchant
Speaking of Grindstone, when combining with the grindstone, it will consume the tools as expected, confirming my theory
