### ISSUE TITLE
Machines Overclock the Number of Times of Their Tier, but not to Their Tier

### ISSUE THREAD

**Issue by voidsong-dragonfly** [GregTechCEu/GregTechCEu-1.19#961]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3b

### Recipe Viewer Installed

EMI

### Environment

Dedicated Server

### Cross-Mod Interaction

Unsure

### Other Installed Mods

SkyGreg 1.21

### Expected Behavior

Recipes in machines should overclock to the maximum EU/t of their tier or one overclock below it. A 2EU/t ULV recipe should overclock to 32EU/t in a LV machine, or 512EU/t in an HV machine. A 7EU/t recipe should overclock to 448EU/t in HV, etc.

### Actual Behavior

Machines overclock to their tier/LV number of times. A 2EU/t recipe in a HV machine becomes 32EU/t and a LV recipe.

### Steps to Reproduce

A low power recipe used in a high tier machine will not overclock properly, such as sugar cane compressing for plant balls.
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/40431605/aa3886eb-53a6-4a7f-8f61-003228649ebf)

**Comment by moozilla** [comment]
Pretty sure this behavior is intentional. Max number of overclocks is determined by machine tier minus the recipe tier (excluding ULV). See: https://github.com/GregTechCEu/GregTech-Modern/blob/5f9f2d8/src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeHelper.java#L88-L100

In the community pack quest book it mentions that the 2 EU/t LV recipes were set up this way on purpose so when overclocked to HV they could run in an LV line. (Since `2 * 4 * 4 = 32`, which is the max an LV cable can support.)

**Comment by voidsong-dragonfly** [comment]
Fair enough! That's not how I would have done it but I can see some of the logic of that.
